parameters:
  slnPath : 'XGraphics.sln'
  nugetVersion: '5.2.0'

steps:
- task: NuGetToolInstaller@0
  displayName: 'Use NuGet ${{ parameters.nugetVersion }}'
  inputs:
    versionSpec: ${{ parameters.nugetVersion }}

- task: NuGetCommand@2
  displayName: 'NuGet restore ${{ parameters.slnPath }}'
  inputs:
    restoreSolution: ${{ parameters.slnPath }}
